# Generated by Django 5.2 on 2025-04-25 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('ST', 'Студент'), ('TE', 'Преподаватель'), ('AD', 'Администратор')], max_length=2, verbose_name='Роль')),
                ('group', models.CharField(blank=True, max_length=20, null=True, verbose_name='Группа')),
                ('academic_rating', models.FloatField(default=0, verbose_name='Учебный рейтинг')),
                ('activity_rating', models.FloatField(default=0, verbose_name='Внеучебный рейтинг')),
                ('academic_change', models.FloatField(default=0, verbose_name='Изменение учебного рейтинга')),
                ('activity_change', models.FloatField(default=0, verbose_name='Изменение внеучебного рейтинга')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
