# Generated by Django 5.2 on 2025-05-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achieve_id', models.AutoField(primary_key=True, serialize=False)),
                ('achieve_name', models.CharField(max_length=100, verbose_name='Название достижения')),
                ('achieve_description', models.TextField(verbose_name='Описание достижения')),
                ('condition', models.TextField(verbose_name='Условия получения')),
                ('achieve_photo', models.ImageField(blank=True, null=True, upload_to='achievement_photos/', verbose_name='Фото достижения')),
                ('reward_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда (денежная)')),
            ],
        ),
        migrations.CreateModel(
            name='Event_roles',
            fields=[
                ('e_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_role_name', models.CharField(max_length=50, verbose_name='Название роли')),
                ('points', models.PositiveIntegerField(verbose_name='Баллы за роль')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('event_name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('place', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='event_photos/', verbose_name='Фото мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('merch_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Тип товара')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('merch_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('merch_photo', models.ImageField(blank=True, null=True, upload_to='merch_photos/', verbose_name='Фото товара')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='academic_change',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='academic_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity_change',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ST', 'Студент'), ('TE', 'Преподаватель'), ('AD', 'Администратор'), ('MA', 'Менеджер'), ('PR', 'Продавец')], max_length=2, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='MoneyOperations',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('for_what', models.CharField(max_length=100, verbose_name='На что потрачено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_operations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('merch_count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order_summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.merch', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.BooleanField(default=False, verbose_name='Посещение')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('e_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.event_roles', verbose_name='Роль на мероприятии')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.events', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='students',
            field=models.ManyToManyField(related_name='groups_joined', through='main.StudentGroupMembership', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('semestr_id', models.IntegerField(verbose_name='Семестр')),
                ('subject_type', models.CharField(max_length=50, verbose_name='Тип предмета')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.groups', verbose_name='Группа')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taught', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grades_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.FloatField(verbose_name='Оценка')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.subjects', verbose_name='Предмет')),
            ],
        ),
    ]
