# Generated by Django 5.2 on 2025-05-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievements_event_roles_events_groups_merch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_roles',
            new_name='EventRoles',
        ),
        migrations.AlterField(
            model_name='moneyoperations',
            name='for_what',
            field=models.CharField(max_length=100, verbose_name='За что'),
        ),
    ]
