# Generated by Django 5.2 on 2025-05-11 02:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyoperations',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
