# Generated by Django 5.2 on 2025-05-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_moneyoperations_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-order_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
